- name: east-tec Eraser
  role: original creator & developer
  url:  https://www.east-tec.com/eraser/

- name: east-tec DisposeSecure
  role: original creator & developer
  url:  https://www.east-tec.com/disposesecure/

- name: CyberScrub
  role: original creator & developer
  url:

- name: cyberCide
  role: original creator & developer
  url:

- name: east-tec FormatSecure
  role: creator & developer
  url:  https://web.archive.org/web/20050509180501/http://www.east-tec.com/formatsc/

- name: diskSpace Explorer
  role: creator & developer
  url:  https://web.archive.org/web/20060406190416/http://www.east-tec.com/diskmanager/
